# Generated by Django 5.1.15 on 2026-04-17 22:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150)),
                ('nombre_fantasia', models.CharField(blank=True, max_length=150, null=True)),
                ('cuit', models.CharField(max_length=13, unique=True)),
                ('ingresos_brutos', models.CharField(blank=True, max_length=50, null=True)),
                ('actividad_principal', models.CharField(max_length=200)),
                ('actividad_secundaria', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_empresa', models.CharField(choices=[('Nueva', 'Nueva'), ('Existente', 'Existente')], max_length=20)),
                ('objetivo_proyecto', models.CharField(blank=True, choices=[('Traslado', 'Traslado total o parcial'), ('NuevosProductos', 'Elaborar nuevos productos'), ('IncrementarProduccion', 'Incrementar producción total'), ('InstalacionNueva', 'Instalación nueva'), ('Reconversion', 'Reconversión productiva'), ('Ampliacion', 'Ampliación de planta')], max_length=50, null=True)),
                ('rubro', models.CharField(choices=[('Servicios', 'Servicios'), ('Bienes', 'Bienes'), ('BienesYServicios', 'Bienes y Servicios'), ('Metalurgica', 'Metalúrgica'), ('Maderera', 'Maderera'), ('Textil', 'Textil'), ('Agroindustria', 'Agroindustria'), ('Construccion', 'Construcción'), ('Logistica', 'Logística'), ('Otro', 'Otro')], max_length=30)),
                ('descripcion_actividad', models.TextField()),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('persona_referente', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=30)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('emplazamiento_actual', models.CharField(blank=True, choices=[('Propio', 'Propio'), ('Alquilado', 'Alquilado')], max_length=20, null=True)),
                ('personal_jerarquico', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('personal_produccion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('personal_administrativo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('personal_a_ocupar', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('materias_primas', models.TextField(blank=True, null=True)),
                ('destino_produccion', models.TextField(blank=True, null=True)),
                ('necesidad_m2', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('superficie_cubierta_trabajo_m2', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('superficie_cubierta_deposito_m2', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('superficie_futura_expansion_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('superficie_estacionamiento_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tiene_planos', models.BooleanField()),
                ('tiempo_radicacion_meses', models.IntegerField(choices=[(6, '6 Meses'), (12, '12 Meses'), (24, '24 Meses'), (36, '36 o más Meses')])),
                ('energia_tension', models.CharField(blank=True, choices=[('Media', 'Media Tensión'), ('Baja', 'Baja Tensión')], max_length=10, null=True)),
                ('energia_potencia_rango', models.CharField(blank=True, choices=[('Hasta10', 'Hasta 10 kW'), ('10a50', '10 – 50 kW'), ('50a100', '50 – 100 kW'), ('100a500', '100 – 500 kW'), ('Mas500', 'Más de 500 kW')], max_length=20, null=True)),
                ('consumo_estimado_agua_potable', models.CharField(blank=True, choices=[('Hasta50', 'Hasta 50 m³/mes'), ('50a200', '50 – 200 m³/mes'), ('200a500', '200 – 500 m³/mes'), ('Mas500', 'Más de 500 m³/mes')], max_length=20, null=True)),
                ('consumo_estimado_agua_cruda', models.CharField(blank=True, choices=[('Hasta50', 'Hasta 50 m³/mes'), ('50a200', '50 – 200 m³/mes'), ('200a500', '200 – 500 m³/mes'), ('Mas500', 'Más de 500 m³/mes')], max_length=20, null=True)),
                ('gas', models.BooleanField(default=False)),
                ('requiere_internet', models.BooleanField(default=False)),
                ('necesidad_balanza_publica', models.BooleanField(default=False)),
                ('necesidad_comedor', models.BooleanField(default=False)),
                ('necesidad_salon_multiuso', models.BooleanField(default=False)),
                ('categoria_industrial', models.CharField(choices=[('Alimenticia', 'Alimenticia'), ('Quimica', 'Química'), ('Tecnologica', 'Tecnológica'), ('Otro', 'Otro')], max_length=30)),
                ('maneja_inflamables', models.BooleanField(default=False)),
                ('genera_residuos', models.BooleanField(default=False)),
                ('residuos_efluentes', models.TextField(blank=True, null=True)),
                ('tratamiento_en_planta', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('EnEvaluacion', 'En Evaluación'), ('PreAprobado', 'Pre-Aprobado'), ('Rechazado', 'Rechazado'), ('Radicada', 'Radicada'), ('EnConstruccion', 'En Construcción'), ('Finalizado', 'Finalizado'), ('Escriturado', 'Escriturado'), ('Caducado', 'Caducado'), ('Historico_Baja', 'Clausurado / Baja')], default='EnEvaluacion', max_length=30)),
                ('fecha_limite_obra', models.DateField(blank=True, null=True)),
                ('escritura_pdf', models.FileField(blank=True, null=True, upload_to='escrituras/')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='AvanceConstructivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_declarado', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('certificado_pdf', models.FileField(upload_to='certificados/')),
                ('fecha_presentacion', models.DateField(auto_now_add=True)),
                ('validado_admin', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_constructivos', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Avance Constructivo',
                'verbose_name_plural': 'Avances Constructivos',
                'ordering': ['-fecha_presentacion'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_parcela', models.IntegerField(unique=True)),
                ('superficie_m2', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('conexion_agua_potable', models.BooleanField(default=False)),
                ('conexion_agua_cruda', models.BooleanField(default=False)),
                ('internet_disponible', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('EnUso', 'En Uso'), ('ReservaFiscal', 'Reserva Fiscal')], default='Disponible', max_length=30)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='core.empresa')),
                ('lotes_colindantes', models.ManyToManyField(blank=True, to='core.lote')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['nro_parcela'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudProrroga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses_solicitados', models.IntegerField(choices=[(6, '6 Meses'), (12, '12 Meses'), (24, '24 Meses'), (36, '36 o más Meses')])),
                ('justificacion', models.TextField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('respuesta_admin', models.TextField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prorrogas', to='core.empresa')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prorrogas_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Prórroga',
                'verbose_name_plural': 'Solicitudes de Prórroga',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='TransicionEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('EnEvaluacion', 'En Evaluación'), ('PreAprobado', 'Pre-Aprobado'), ('Rechazado', 'Rechazado'), ('Radicada', 'Radicada'), ('EnConstruccion', 'En Construcción'), ('Finalizado', 'Finalizado'), ('Escriturado', 'Escriturado'), ('Caducado', 'Caducado'), ('Historico_Baja', 'Clausurado / Baja')], max_length=30, null=True)),
                ('estado_nuevo', models.CharField(choices=[('EnEvaluacion', 'En Evaluación'), ('PreAprobado', 'Pre-Aprobado'), ('Rechazado', 'Rechazado'), ('Radicada', 'Radicada'), ('EnConstruccion', 'En Construcción'), ('Finalizado', 'Finalizado'), ('Escriturado', 'Escriturado'), ('Caducado', 'Caducado'), ('Historico_Baja', 'Clausurado / Baja')], max_length=30)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('justificacion_resolucion', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transiciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transición de Estado',
                'verbose_name_plural': 'Transiciones de Estado',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('periodo_anio', models.IntegerField(validators=[django.core.validators.MinValueValidator(2024)])),
                ('consumo_agua_potable_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('consumo_agua_cruda_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('consumo_luz_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('consumo_gas_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('cargado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_cargados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Consumo de Servicio',
                'verbose_name_plural': 'Consumos de Servicios',
                'ordering': ['-periodo_anio', '-periodo_mes'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'periodo_mes', 'periodo_anio'), name='unique_consumo_periodo')],
            },
        ),
    ]
