# Generated by Django 5.1.15 on 2026-04-23 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('InformaticoMobiliario', 'Informático / Mobiliario de Oficina'), ('EquipamientoMantenimiento', 'Equipamiento de Mantenimiento')], max_length=40, verbose_name='Categoría')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del activo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('codigo_inventario', models.CharField(help_text='Generado automáticamente. Formato: INF-YYYYNNN / MNT-YYYYNNN.', max_length=20, unique=True, verbose_name='Código de inventario')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de serie')),
                ('fecha_alta', models.DateField(verbose_name='Fecha de alta')),
                ('estado', models.CharField(choices=[('EnUso', 'En uso'), ('EnDeposito', 'En depósito'), ('EnReparacion', 'En reparación'), ('DeBaja', 'De baja')], default='EnUso', max_length=30, verbose_name='Estado')),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar equivale a dar de baja el activo (baja lógica). El registro se conserva.', verbose_name='Activo')),
                ('motivo_baja', models.TextField(blank=True, help_text='Obligatorio al dar de baja el activo.', null=True, verbose_name='Motivo de baja')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('dado_de_baja_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas_de_inventario_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Dado de baja por')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Activo de Inventario',
                'verbose_name_plural': 'Inventario',
                'ordering': ['categoria', 'codigo_inventario'],
                'indexes': [models.Index(fields=['categoria', 'activo'], name='idx_activo_cat_activo'), models.Index(fields=['estado'], name='idx_activo_estado')],
            },
        ),
    ]
