# Generated by Django 5.1.15 on 2026-04-14 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumoservicio',
            name='consumo_gas_m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='empresa',
            name='escritura_pdf',
            field=models.FileField(blank=True, null=True, upload_to='escrituras/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_fantasia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=models.CharField(choices=[('EnEvaluacion', 'En Evaluación'), ('PreAprobado', 'Pre-Aprobado'), ('Rechazado', 'Rechazado'), ('Radicada', 'Radicada'), ('EnConstruccion', 'En Construcción'), ('Finalizado', 'Finalizado'), ('Escriturado', 'Escriturado'), ('Caducado', 'Caducado'), ('Historico_Baja', 'Clausurado / Baja')], default='EnEvaluacion', max_length=30),
        ),
        migrations.AlterField(
            model_name='transicionestado',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('EnEvaluacion', 'En Evaluación'), ('PreAprobado', 'Pre-Aprobado'), ('Rechazado', 'Rechazado'), ('Radicada', 'Radicada'), ('EnConstruccion', 'En Construcción'), ('Finalizado', 'Finalizado'), ('Escriturado', 'Escriturado'), ('Caducado', 'Caducado'), ('Historico_Baja', 'Clausurado / Baja')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transicionestado',
            name='estado_nuevo',
            field=models.CharField(choices=[('EnEvaluacion', 'En Evaluación'), ('PreAprobado', 'Pre-Aprobado'), ('Rechazado', 'Rechazado'), ('Radicada', 'Radicada'), ('EnConstruccion', 'En Construcción'), ('Finalizado', 'Finalizado'), ('Escriturado', 'Escriturado'), ('Caducado', 'Caducado'), ('Historico_Baja', 'Clausurado / Baja')], max_length=30),
        ),
    ]
