# Generated by Django 5.1.15 on 2026-04-14 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_consumoservicio_consumo_gas_m3_empresa_escritura_pdf_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudProrroga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meses_solicitados",
                    models.IntegerField(
                        choices=[
                            (6, "6 Meses"),
                            (12, "12 Meses"),
                            (24, "24 Meses"),
                            (36, "36 o más Meses"),
                        ]
                    ),
                ),
                ("justificacion", models.TextField()),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("Aprobada", "Aprobada"),
                            ("Rechazada", "Rechazada"),
                        ],
                        default="Pendiente",
                        max_length=20,
                    ),
                ),
                ("respuesta_admin", models.TextField(blank=True, null=True)),
                ("fecha_respuesta", models.DateTimeField(blank=True, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prorrogas",
                        to="core.empresa",
                    ),
                ),
                (
                    "resuelta_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prorrogas_resueltas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Prórroga",
                "verbose_name_plural": "Solicitudes de Prórroga",
                "ordering": ["-fecha_solicitud"],
            },
        ),
    ]
