# Generated by Django 5.1.15 on 2026-04-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_solicitud_prorroga'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='genera_residuos',
            field=models.BooleanField(default=False),
        ),
    ]
