# Generated by Django 5.1.15 on 2026-05-15 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_solicitudacceso_documentacion_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='alto_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alto (m)'),
        ),
        migrations.AddField(
            model_name='lote',
            name='ancho_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ancho (m)'),
        ),
        migrations.AddField(
            model_name='lote',
            name='mapa_h',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mapa: alto'),
        ),
        migrations.AddField(
            model_name='lote',
            name='mapa_w',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mapa: ancho'),
        ),
        migrations.AddField(
            model_name='lote',
            name='mapa_x',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mapa: X'),
        ),
        migrations.AddField(
            model_name='lote',
            name='mapa_y',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mapa: Y'),
        ),
    ]
