
# Nginx config (nginx/nginx.conf)
upstream gpiv_app {
    server web:8000;
}

# Bloque para la App de Gestión
server {
    listen 80;
    server_name gpiv.tivena.com.ar;

    location /static/ {
        alias /app/staticfiles/;
    }

    location / {
        proxy_pass http://gpiv_app;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# Bloque para la futura Landing de la empresa
server {
    listen 80;
    server_name tivena.com.ar; 
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
